import type { Metadata } from "next";
import { Nunito, PT_Sans } from "next/font/google";
import "@/styles/globals.css";
import { Footer } from "@/components/footer";
import Image from "next/image";
import { Header } from "@/components/header";
import { Providers } from "@/components/providers";
import { ViewTransitions } from "next-view-transitions";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const ptSans = PT_Sans({
  variable: "--font-pt-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Ignitia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${nunito.variable} ${ptSans.variable} antialiased relative bg-background text-foreground`}
        >
          <Providers>
            <Header />
            <main
              id="skip-nav"
              className="mx-auto mb-16 w-full flex-1 px-4 py-12 sm:px-8"
            >
              {children}
            </main>
            <Footer />
            <Image
              width={1512}
              height={550}
              className="absolute left-1/2 top-0 -z-10 -translate-x-1/2"
              src="/gradient-background-top.png"
              alt=""
              role="hello"
              priority
            />
          </Providers>
        </body>
      </html>
    </ViewTransitions>
  );
}
